import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { markdownToSlackMrkdwn } from '../src/index.js'

interface Fixture {
  in: string
  w?: number
  out: string
}

// Generated by parity/export-fixtures.ts from the Go converter's output; a failure means the TS port drifted from Go.
const fixtures = JSON.parse(readFileSync(new URL('./fixtures.json', import.meta.url), 'utf8')) as Fixture[]

test('matches the Go converter on every fixture', () => {
  const failures: string[] = []
  for (const f of fixtures) {
    const got = markdownToSlackMrkdwn(f.in, f.w === undefined ? {} : { maxTableWidth: f.w })
    if (got !== f.out) failures.push(`${JSON.stringify(f.in)} (width ${f.w ?? 'default'})\n  want ${JSON.stringify(f.out)}\n  got  ${JSON.stringify(got)}`)
  }
  assert.equal(failures.length, 0, `${failures.length} of ${fixtures.length} fixtures differ:\n${failures.slice(0, 5).join('\n')}`)
})
