// Generates src/goldmark/casefold.ts from goldmark's unicode_case_folding.gen.go (run by hand when goldmark is updated).
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { repoRoot } from './golib.js'

const dir = execFileSync(
  'go',
  ['list', '-m', '-f', '{{.Dir}}', 'github.com/yuin/goldmark'],
  { cwd: repoRoot }
)
  .toString()
  .trim()
const src = readFileSync(`${dir}/util/unicode_case_folding.gen.go`, 'utf8')
const list = (name: string): number[] => {
  const m = new RegExp(`var ${name} = \\[\\.\\.\\.\\]\\w+\\{([^}]*)\\}`).exec(
    src
  )
  if (!m) throw new Error(`missing ${name}`)
  return m[1]!
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean)
    .map((x) => Number(x))
}
const from = list('_unicodeCaseFoldingFrom')
const toIndexSrc = /var _unicodeCaseFoldingToIndex\s*=\s*"([^"]*)"/.exec(src)
if (!toIndexSrc) throw new Error('missing _unicodeCaseFoldingToIndex')
const toIndex = [...toIndexSrc[1]!.matchAll(/\\x([0-9a-f]{2})/g)].map((m) =>
  parseInt(m[1]!, 16)
)
const to = list('_unicodeCaseFoldingTo')
const entries: Array<{ from: number; to: number[] }> = []
let at = 0
from.forEach((f, i) => {
  entries.push({ from: f, to: to.slice(at, at + toIndex[i]!) })
  at += toIndex[i]!
})

// Runs of single-rune folds with a constant step and delta: [start, count, step, delta]; everything else is listed as [from, ...to].
const runs: number[][] = []
const rest: number[][] = []
for (let i = 0; i < entries.length;) {
  const e = entries[i]!
  if (e.to.length === 1) {
    const delta = e.to[0]! - e.from
    let j = i + 1
    const step = j < entries.length ? entries[j]!.from - e.from : 0
    while (
      j < entries.length &&
      entries[j]!.to.length === 1 &&
      entries[j]!.to[0]! - entries[j]!.from === delta &&
      entries[j]!.from - entries[j - 1]!.from === step
    )
      j++
    if (j - i >= 4) {
      runs.push([e.from, j - i, step, delta])
      i = j
      continue
    }
  }
  rest.push([e.from, ...e.to])
  i++
}
const hex = (n: number): string => n.toString(16)
const out = `// Generated by parity/gen-casefold.ts from goldmark's unicode_case_folding table. Do not edit.

const RUNS = '${runs.map((r) => r.map((n) => (n < 0 ? '-' + hex(-n) : hex(n))).join(',')).join(';')}'
const OTHERS = '${rest.map((r) => r.map(hex).join(',')).join(';')}'

/** Full Unicode case folding as goldmark applies it to link labels: code point to folded string. */
export const CASE_FOLDING: ReadonlyMap<number, string> = (() => {
  const map = new Map<number, string>()
  for (const run of RUNS.split(';')) {
    const [start = 0, count = 0, step = 0, delta = 0] = run.split(',').map((x) => parseInt(x, 16))
    for (let i = 0; i < count; i++) map.set(start + i * step, String.fromCodePoint(start + i * step + delta))
  }
  for (const entry of OTHERS.split(';')) {
    const [cp = 0, ...folded] = entry.split(',').map((x) => parseInt(x, 16))
    map.set(cp, String.fromCodePoint(...folded))
  }
  return map
})()
`
writeFileSync(new URL('../src/goldmark/casefold.ts', import.meta.url), out)
console.log(
  `entries ${entries.length}, runs ${runs.length}, others ${rest.length}, bytes ${out.length}`
)
