// Generates src/entities.ts from Go's html entity table (WHATWG named character references).
import { readFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const goroot = execSync('go env GOROOT').toString().trim()
const src = readFileSync(`${goroot}/src/html/entity.go`, 'utf8')
const single = [
  ...src.matchAll(/^\s*"([A-Za-z0-9;]+)":\s*'\\[uU]([0-9A-Fa-f]{4,8})',/gm),
]
const double = [
  ...src.matchAll(
    /^\s*"([A-Za-z0-9;]+)":\s*\{'\\[uU]([0-9A-Fa-f]{4,8})', '\\[uU]([0-9A-Fa-f]{4,8})'\},/gm
  ),
]
const entries: string[] = []
const legacy: string[] = []
const add = (name: string, cps: string[]) => {
  if (!name.endsWith(';')) return void legacy.push(name)
  entries.push(
    `${name.slice(0, -1)}=${cps.map((c) => parseInt(c, 16).toString(16)).join(',')}`
  )
}
for (const m of single) add(m[1]!, [m[2]!])
for (const m of double) add(m[1]!, [m[2]!, m[3]!])
entries.sort()
legacy.sort()
const out = `// Generated by parity/gen-entities.ts from Go's html entity table. Do not edit.

const ENTITIES = '${entries.join(';')}'
const LEGACY = '${legacy.join(' ')}'

let table: Map<string, string> | undefined

/** The decoded value of a named character reference, given its name without & and ;. */
export function namedEntity(name: string): string | undefined {
  if (table === undefined) {
    table = new Map()
    for (const entry of ENTITIES.split(';')) {
      const [key = '', value = ''] = entry.split('=')
      table.set(key, String.fromCodePoint(...value.split(',').map((x) => parseInt(x, 16))))
    }
  }
  return table.get(name)
}

/** Names Go also accepts without the closing semicolon. */
export const LEGACY_ENTITIES: ReadonlySet<string> = new Set(LEGACY.split(' '))
`
writeFileSync(new URL('../src/entities.ts', import.meta.url), out)
console.log(
  `entities ${entries.length}, legacy ${legacy.length}, bytes ${out.length}`
)
